AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OnConnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "onConnect"
      CodeUri: onConnect/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ws_lambda_role
  OnDisconnect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "onDisconnect"
      CodeUri: onDisconnect/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ws_lambda_role
  OnDefault:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "onDefault"
      CodeUri: onDefault/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ws_lambda_role
  SendMessage:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "sendMessage"
      CodeUri: sendMessage/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ws_lambda_role
